Proy_AdminVtasWeb/Areas/Usuario/Controllers/PedidoController.cs
using AdminVtasWeb.CapaEntity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Globalization;

namespace Proy_AdminVtasWeb.Areas.Usuario.Controllers
{
    [Area("Usuario")]
    public class PedidoController : Controller
    {
        private readonly string cadenaSQL;

        public IActionResult Index()
        {
            return View();
        }

        public PedidoController(IConfiguration configuration)
        {
            cadenaSQL = configuration.GetConnectionString("SQLConexion");
        }
        public IActionResult CargaPedido()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CargaPedido(Pedido pedido)
        {
            using (SqlConnection con = new(cadenaSQL))
            {
                using (SqlCommand cmd = new("sp_guardaPedido", con))
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.Add("@codigo", System.Data.SqlDbType.VarChar).Value = pedido.codigo;
                    cmd.Parameters.Add("@IdSucursal", System.Data.SqlDbType.Int).Value = 1;
                    cmd.Parameters.Add("@Cliente", System.Data.SqlDbType.VarChar).Value = pedido.Cliente;
                    cmd.Parameters.Add("@Cantidad", System.Data.SqlDbType.Int).Value = pedido.Cantidad;
                    cmd.Parameters.Add("@Estado", System.Data.SqlDbType.Int).Value = 1;
                    con.Open();
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
            }
            return Redirect("Index");
        }


        public IActionResult TraeVenta()
        {
            return View();
        }
        [HttpGet]
        public IActionResult TraeVenta(Venta venta)
        {
            using (SqlConnection con = new(cadenaSQL))
            {
                using (SqlCommand cmd = new("sp_PedidoCliente", con))
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.Add("@Cliente", System.Data.SqlDbType.VarChar).Value = "vaguilar@live.com";
                    con.Open();
                    SqlDataAdapter da = new(cmd);
                    DataTable dt = new();
                    da.Fill(dt);
                    da.Dispose();

                    List<Venta> lista = new();
                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        lista.Add(new Venta()
                        {
                            IdPedido = Convert.ToInt32(dt.Rows[i][1].ToString()),
                            Sucursal = (dt.Rows[i][3].ToString()),
                            Descripcion = (dt.Rows[i][4].ToString()),
                            Cliente = (dt.Rows[i][5].ToString()),
                            Cantidad = Convert.ToInt32(dt.Rows[i][7].ToString()),
                        });
                    }
                    ViewBag.Venta = lista;
                    con.Close();
                }
                return View();
            }

        }

        public JsonResult obtenerArticulo(string codigo, string b_descripcion, string b_descripcion2)
        {
            using (SqlConnection con = new(cadenaSQL))
            {
                List<Artículo> lista = new();
                using (SqlCommand cmd = new("sp_CatArticulo", con))
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.Add("@CodArticulo", System.Data.SqlDbType.VarChar).Value = "vaguilar@live.com";
                    con.Open();
                    SqlDataAdapter da = new(cmd);
                    DataTable dt = new();
                    da.Fill(dt);
                    da.Dispose();


                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        lista.Add(new Artículo()
                        {
                            IdArticulo = Convert.ToInt32(dt.Rows[i][0].ToString()),
                            Codigo = (dt.Rows[i][1].ToString()),
                            Descripcion = (dt.Rows[i][2].ToString()),
                        });
                    }
                    con.Close();
                }
                return Json(lista);
            }

        }

    }
}

Proy_AdminVtasWeb/Areas/Usuario/Views/Pedido/CargaPedido.cshtml
@model AdminVtasWeb.CapaEntity.Pedido
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Carga Pedido";
}
<h1>Crea Pedido Articulos</h1>
@* <h4>@User.Identity?.Name</h4> *@
<form method="post" class="form-floating">

    <div class="form-group">
        <label class="form-label">Articulo</label>
        <select class="form-select form-select-sm" asp-for="codigo" id="cbocodigo" />
     </div>
    <div class="form-group">
        <br/>
        @* <label asp-for="Cliente" ></label> *@
        <label asp-for="Cliente" id="Usuario" >Usuario</label>
        <input class="form-control" visible="false" asp-for="Cliente" value="@User.Identity?.Name" />
    </div>
    <div class="form-group">
        <label asp-for="Cantidad"></label>
        <input class="form-control" asp-for="Cantidad" />
    </div>
    <br />
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
    </div>

</form>


@section Scripts{
    <script>
        $(document).ready(function (){
            obtenerArticulos()
        })
        var _IdArticulo = $("#cbocodigo option:selected").val()
        function obtenerArticulos() {
            $.ajax({
                url: "@Url.Action("obtenerArticulo", "Pedido")",
                type: "GET",
                dataType:"json",
                data: {
                    codigo: "",
                    codigo: "b_descripcion",
                    codigo: "b_descripcion2"
                },
                success: function (response) {
                    console.log(response)

                    $("#cbocodigo").append(
                        $("<option>").attr({ "value": "" }).text("Seleccionar")
                    )

                    $.each(response, function(i, elemento){
                        $("#cbocodigo").append(
                            $("<option>").attr({ "value": elemento.codigo }).text(elemento.descripcion   )
                        )
                    })

                    $("#cbocodigo").select2({ placeholder: "Seleccionar", width: "50%" });


                }
            })
        }
    </script>






}

Proy_AdminVtasWeb/Areas/Usuario/Views/Pedido/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Proy_AdminVtasWeb/Areas/Usuario/Views/Pedido/TraeVenta.cshtml
@{
    ViewData["Title"] = "Detalle Inventario";
}
<br />
<div class="text-center">
    <h5 class="display-6">Pedido del Cliente: @User.Identity?.Name </h5>
    <br />
    <div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="text-light bg-dark">IdPedido</th>
                    <th class="text-light bg-dark">Sucursal</th>
                    <th class="text-light bg-dark">Articulo</th>
                    <th class="text-light bg-dark">Cliente</th>
                    @* <th class="text-light bg-dark">Precio</th> *@
                    <th class="text-light bg-dark">Cantidad</th>
@*                     <th class="text-light bg-dark">Importe Venta</th> *@
                </tr>
            </thead>
            @{
                if (ViewBag.Venta != null)
                {
                    foreach (var item in ViewBag.Venta)
                    {
                        <tr class="table-secondary">
                            <td>@item.IdPedido  </td>
                            <td>@item.Sucursal  </td>
                            <td>@item.Descripcion  </td>
                            <td>@item.Cliente  </td>
                            <td>@item.Cantidad  </td>
                        </tr>
                    }
                }
            }
        </table>
    </div>
</div>